# Source directories
src.dir=src/main/java
resources.dir=src/main/resources
web.dir=src/main/webapp
test.dir=src/test/java

# Build directories
build.dir=build
classes.dir=${build.dir}/classes
test.classes.dir=${build.dir}/test-classes

# Distribution
dist.dir=dist
war.name=lab3.war

# Libraries
lib.dir=lib

# Manifest
manifest.file=MANIFEST.MF

# Java version
java.version=17

# Music - need to add
music.file=music.mp3

# Git tracked classes
git.classes=PointResult.java,ResultsBean.java